In [11]:
import numpy as np
import cv2

# 동영상 파일 경로
video_path = 'test.mp4'

# 체스보드의 가로 및 세로 내부 코너 수
chessboard_size = (7, 5)

# 체스보드의 3D 좌표 생성
objp = np.zeros((np.prod(chessboard_size), 3), dtype=np.float32)
objp[:, :2] = np.mgrid[0:chessboard_size[0], 0:chessboard_size[1]].T.reshape(-1, 2)

# 3D 포인트와 2D 포인트를 저장할 리스트
objpoints = []  # 3D 포인트
imgpoints = []  # 2D 포인트

# 동영상 열기
cap = cv2.VideoCapture(video_path)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # 체스보드 코너를 찾음
    ret, corners = cv2.findChessboardCorners(gray, chessboard_size, None)

    if ret == True:
        objpoints.append(objp)
        imgpoints.append(corners)

        # 코너를 그림
        frame = cv2.drawChessboardCorners(frame, chessboard_size, corners, ret)

    cv2.imshow('frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

# 카메라 캘리브레이션 수행
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

# 캘리브레이션 결과 출력
print("Camera Matrix:")
print(mtx)
print("\nDistortion Coefficients:")
print(dist)

Camera Matrix:
[[434.57252885   0.         584.91073356]
 [  0.         428.72867494 306.83691191]
 [  0.           0.           1.        ]]

Distortion Coefficients:
[[ 0.34435202 -1.05326327  0.03865779  0.00777132  1.33774711]]
